# Generated by Django 4.2.13 on 2024-11-24 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='education',
            old_name='end_date',
            new_name='endDate',
        ),
        migrations.RenameField(
            model_name='education',
            old_name='start_date',
            new_name='startDate',
        ),
    ]
