# Generated by Django 4.2.13 on 2024-12-03 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workexperience', '0002_rename_end_date_workexperience_enddate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workexperience',
            name='achievements',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
