# Generated by Django 4.2.13 on 2024-11-25 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('header', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='header',
            name='address',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='header',
            name='location',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='header',
            name='phone',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='header',
            name='socialmedia',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='header',
            name='url',
            field=models.URLField(default=''),
        ),
    ]
