# Generated by Django 4.2.13 on 2024-11-25 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('header', '0002_header_address_header_location_header_phone_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='header',
            old_name='location',
            new_name='email',
        ),
    ]
